/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { ERC20Test06, ERC20Test06Interface } from "../ERC20Test06";

const _abi = [
  {
    inputs: [],
    name: "DECIMALS",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "NAME",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SYMBOL",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610227806100206000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c806301ffc9a7146100515780632e0f2625146100bb578063a3f4df7e146100d5578063f76f8d781461011e575b600080fd5b6100a661005f36600461015a565b7fffffffff00000000000000000000000000000000000000000000000000000000167f7b6bbd84000000000000000000000000000000000000000000000000000000001490565b60405190151581526020015b60405180910390f35b6100c3600981565b60405160ff90911681526020016100b2565b6101116040518060400160405280601b81526020017f506172656e742053657276696365436861696e546f6b656e203036000000000081525081565b6040516100b291906101a3565b6101116040518060400160405280600681526020017f505343543036000000000000000000000000000000000000000000000000000081525081565b60006020828403121561016c57600080fd5b81357fffffffff000000000000000000000000000000000000000000000000000000008116811461019c57600080fd5b9392505050565b600060208083528351808285015260005b818110156101d0578581018301518582016040015282016101b4565b506000604082860101526040601f19601f830116850101925050509291505056fea2646970667358221220f2b344ff56264802dbe05be8bb687ae3f6aba2f8e2412913d0aef57ef25384a264736f6c63430008110033";

export class ERC20Test06__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ERC20Test06> {
    return super.deploy(overrides || {}) as Promise<ERC20Test06>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ERC20Test06 {
    return super.attach(address) as ERC20Test06;
  }
  connect(signer: Signer): ERC20Test06__factory {
    return super.connect(signer) as ERC20Test06__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ERC20Test06Interface {
    return new utils.Interface(_abi) as ERC20Test06Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC20Test06 {
    return new Contract(address, _abi, signerOrProvider) as ERC20Test06;
  }
}
