/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IERC721BridgeReceiver,
  IERC721BridgeReceiverInterface,
} from "../IERC721BridgeReceiver";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "_from",
        type: "address",
      },
      {
        name: "_tokenId",
        type: "uint256",
      },
      {
        name: "_to",
        type: "address",
      },
      {
        name: "_extraData",
        type: "bytes",
      },
    ],
    name: "onERC721Received",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IERC721BridgeReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): IERC721BridgeReceiverInterface {
    return new utils.Interface(_abi) as IERC721BridgeReceiverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC721BridgeReceiver {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IERC721BridgeReceiver;
  }
}
