/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IERC20BridgeReceiver,
  IERC20BridgeReceiverInterface,
} from "../IERC20BridgeReceiver";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "_from",
        type: "address",
      },
      {
        name: "_to",
        type: "address",
      },
      {
        name: "_amount",
        type: "uint256",
      },
      {
        name: "_feeLimit",
        type: "uint256",
      },
      {
        name: "_extraData",
        type: "bytes",
      },
    ],
    name: "onERC20Received",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IERC20BridgeReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): IERC20BridgeReceiverInterface {
    return new utils.Interface(_abi) as IERC20BridgeReceiverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC20BridgeReceiver {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IERC20BridgeReceiver;
  }
}
