/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  NetworkKeyModel,
  NetworkKeyModelInterface,
} from "../NetworkKeyModel";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "chainId",
        type: "string",
      },
      {
        internalType: "string",
        name: "shortName",
        type: "string",
      },
    ],
    name: "getNetworkKey",
    outputs: [
      {
        internalType: "string",
        name: "key",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506102b7806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063cf319e9b14610030575b600080fd5b61004361003e36600461016e565b610059565b60405161005091906101f6565b60405180910390f35b606061007860405180604001604052808581526020018481525061007f565b9392505050565b60608160000151826020015160405160200161009c929190610229565b6040516020818303038152906040529050919050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052604160045260246000fd5b600082601f8301126100f257600080fd5b813567ffffffffffffffff8082111561010d5761010d6100b2565b604051601f8301601f19908116603f01168101908282118183101715610135576101356100b2565b8160405283815286602085880101111561014e57600080fd5b836020870160208301376000602085830101528094505050505092915050565b6000806040838503121561018157600080fd5b823567ffffffffffffffff8082111561019957600080fd5b6101a5868387016100e1565b935060208501359150808211156101bb57600080fd5b506101c8858286016100e1565b9150509250929050565b60005b838110156101ed5781810151838201526020016101d5565b50506000910152565b60208152600082518060208401526102158160408501602087016101d2565b601f01601f19169190910160400192915050565b6000835161023b8184602088016101d2565b7f3a0000000000000000000000000000000000000000000000000000000000000090830190815283516102758160018401602088016101d2565b0160010194935050505056fea2646970667358221220c7096e31b3e98e3f381d1deedd4bd308e2c7436b8b813dab7bb77bef59f9ef0064736f6c63430008110033";

export class NetworkKeyModel__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<NetworkKeyModel> {
    return super.deploy(overrides || {}) as Promise<NetworkKeyModel>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): NetworkKeyModel {
    return super.attach(address) as NetworkKeyModel;
  }
  connect(signer: Signer): NetworkKeyModel__factory {
    return super.connect(signer) as NetworkKeyModel__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): NetworkKeyModelInterface {
    return new utils.Interface(_abi) as NetworkKeyModelInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NetworkKeyModel {
    return new Contract(address, _abi, signerOrProvider) as NetworkKeyModel;
  }
}
